import { requestUrl } from "obsidian";
import type { RequestUrlParam } from "obsidian";

const YOUTUBE_ORIGIN = "https://www.youtube.com";
const TRANSCRIPT_TIMEOUT_MS = 30000;
const MAX_RESPONSE_LENGTH = 5_000_000;
const MAX_CACHED_TRANSCRIPTS = 20;

export interface TranscriptSegment {
	readonly start: number;
	readonly duration: number;
	readonly text: string;
}

export interface VideoTranscript {
	readonly videoId: string;
	readonly language: string;
	readonly languageName: string;
	readonly isAutoGenerated: boolean;
	readonly segments: readonly TranscriptSegment[];
}

interface CaptionTrack {
	baseUrl: string;
	language: string;
	languageName: string;
	isAutoGenerated: boolean;
}

export class TranscriptServiceError extends Error {
	constructor(readonly code: "unavailable" | "blocked" | "network" | "timeout" | "invalid-response", message: string) {
		super(message);
		this.name = "TranscriptServiceError";
	}
}

function record(value: unknown): Record<string, unknown> | undefined {
	return typeof value === "object" && value !== null && !Array.isArray(value)
		? value as Record<string, unknown>
		: undefined;
}

function invalidResponse(): TranscriptServiceError {
	return new TranscriptServiceError("invalid-response", "YouTube returned an unexpected transcript response. Please try again later.");
}

function parseJson(text: string): unknown {
	try {
		return JSON.parse(text);
	} catch {
		throw invalidResponse();
	}
}

// Read a JSON object embedded in a script without evaluating the page's code.
function readPlayerFromHtml(html: string): unknown {
	const match = /(?:var\s+)?ytInitialPlayerResponse\s*=\s*\{/.exec(html);
	if (!match) throw invalidResponse();
	const start = match.index + match[0].length - 1;
	let depth = 0;
	let inString = false;
	let escaped = false;
	for (let index = start; index < html.length; index++) {
		const character = html[index];
		if (inString) {
			if (escaped) escaped = false;
			else if (character === "\\") escaped = true;
			else if (character === '"') inString = false;
		} else if (character === '"') inString = true;
		else if (character === "{") depth++;
		else if (character === "}" && --depth === 0) return parseJson(html.slice(start, index + 1));
	}
	throw invalidResponse();
}

function readTracks(player: unknown): CaptionTrack[] {
	const data = record(player);
	if (!data) throw invalidResponse();
	const status = record(data.playabilityStatus)?.status;
	if (status === "LOGIN_REQUIRED") {
		throw new TranscriptServiceError("blocked", "YouTube requires sign-in or has blocked this transcript request. Try again later.");
	}
	if (status && status !== "OK") {
		throw new TranscriptServiceError("unavailable", "This video is unavailable for transcript fetching.");
	}
	const renderer = record(record(data.captions)?.playerCaptionsTracklistRenderer);
	const tracks = renderer?.captionTracks;
	if (!Array.isArray(tracks) || tracks.length === 0) {
		throw new TranscriptServiceError("unavailable", "No captions are available for this video.");
	}
	return tracks.map((value) => {
		const track = record(value);
		if (!track || typeof track.baseUrl !== "string" || typeof track.languageCode !== "string") throw invalidResponse();
		const name = record(track.name);
		const label = typeof name?.simpleText === "string"
			? name.simpleText
			: name && Array.isArray(name.runs)
				? name.runs.map((run) => record(run)?.text).filter((text) => typeof text === "string").join("")
				: "";
		return { baseUrl: track.baseUrl, language: track.languageCode, languageName: label || track.languageCode, isAutoGenerated: track.kind === "asr" };
	});
}

function selectTrack(tracks: CaptionTrack[], preferredLanguage: string): CaptionTrack {
	const preferred = preferredLanguage.toLowerCase();
	const base = preferred.split("-")[0];
	const languageMatches = [
		(track: CaptionTrack) => track.language.toLowerCase() === preferred,
		(track: CaptionTrack) => track.language.toLowerCase().split("-")[0] === base,
		(track: CaptionTrack) => track.language.toLowerCase().split("-")[0] === "en",
	];
	for (const matches of languageMatches) {
		const track = tracks.find((candidate) => matches(candidate) && !candidate.isAutoGenerated) ?? tracks.find(matches);
		if (track) return track;
	}
	return tracks[0];
}

function segment(start: number, duration: number, text: string): TranscriptSegment {
	if (!Number.isFinite(start) || !Number.isFinite(duration) || start < 0 || duration < 0) throw invalidResponse();
	return { start, duration, text: text.trim() };
}

function decodeHtmlEntities(text: string): string {
	// Escape literal markup so captions stay text during the extra entity decode.
	const document = new DOMParser().parseFromString(`<body>${text.replace(/</g, "&lt;")}`, "text/html");
	return document.body.textContent ?? "";
}

function parseTranscript(text: string): TranscriptSegment[] {
	if (!text.trim()) {
		throw new TranscriptServiceError("blocked", "YouTube returned no caption text. Transcript requests may be temporarily blocked. Try again later.");
	}
	let segments: TranscriptSegment[];
	if (text.trimStart().startsWith("{")) {
		const events = record(parseJson(text))?.events;
		if (!Array.isArray(events)) throw invalidResponse();
		segments = events.flatMap((value) => {
			const event = record(value);
			if (!event || !Array.isArray(event.segs)) return [];
			const content = event.segs.map((part) => {
				const utf8 = record(part)?.utf8;
				if (typeof utf8 !== "string") throw invalidResponse();
				return utf8;
			}).join("");
			return [segment(Number(event.tStartMs) / 1000, Number(event.dDurationMs ?? 0) / 1000, content)];
		});
	} else {
		const document = new DOMParser().parseFromString(text, "text/xml");
		if (document.querySelector("parsererror")) throw invalidResponse();
		const root = document.documentElement.localName;
		if (root !== "transcript" && root !== "timedtext") throw invalidResponse();
		segments = Array.from(document.querySelectorAll(root === "transcript" ? "text" : "body p")).map((element) => {
			// Legacy transcript XML uses seconds; srv3 uses milliseconds.
			const milliseconds = root === "timedtext";
			const start = element.getAttribute(milliseconds ? "t" : "start");
			if (start === null) throw invalidResponse();
			const duration = element.getAttribute(milliseconds ? "d" : "dur") ?? "0";
			const content = Array.from(element.childNodes).map((node) =>
				node.nodeName.toLowerCase() === "br" ? "\n" : node.textContent ?? "",
			).join("");
			return segment(Number(start) / (milliseconds ? 1000 : 1), Number(duration) / (milliseconds ? 1000 : 1), decodeHtmlEntities(content));
		});
	}
	segments = segments.filter((entry) => entry.text.length > 0);
	if (segments.length === 0) throw invalidResponse();
	return segments;
}

export class TranscriptService {
	private cache = new Map<string, VideoTranscript>();

	async getTranscript(videoId: string, signal?: AbortSignal, preferredLanguage = 'en'): Promise<VideoTranscript> {
		if (signal?.aborted) throw new DOMException('Request aborted', 'AbortError');
		const key = `${videoId}:${preferredLanguage.toLowerCase()}`;
		const cached = this.cache.get(key);
		if (cached) {
			this.cache.delete(key);
			this.cache.set(key, cached);
			return cached;
		}
		const transcript = await this.fetchTranscript(videoId, signal, preferredLanguage);
		this.cache.set(key, transcript);
		if (this.cache.size > MAX_CACHED_TRANSCRIPTS) {
			const oldest = this.cache.keys().next().value;
			if (oldest !== undefined) this.cache.delete(oldest);
		}
		return transcript;
	}

	async fetchTranscript(videoId: string, signal?: AbortSignal, preferredLanguage = "en"): Promise<VideoTranscript> {
		if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
			throw new TranscriptServiceError("unavailable", "This video does not have a valid YouTube video ID.");
		}
		let stopReason: Error | undefined = signal?.aborted ? new DOMException("Request aborted", "AbortError") : undefined;
		if (stopReason) throw stopReason;
		let timeoutId: ReturnType<typeof setTimeout> | undefined;
		let abortListener: (() => void) | undefined;
		const stopped = new Promise<never>((_, reject) => {
			timeoutId = setTimeout(() => {
				stopReason = new TranscriptServiceError("timeout", "Transcript fetching timed out. Please try again.");
				reject(stopReason);
			}, TRANSCRIPT_TIMEOUT_MS);
			abortListener = () => {
				stopReason = new DOMException("Request aborted", "AbortError");
				reject(stopReason);
			};
			signal?.addEventListener("abort", abortListener, { once: true });
		});

		// Obsidian requestUrl cannot cancel the underlying HTTP request. Guard every
		// continuation so closing the modal stops subsequent requests and delivery.
		const request = async (options: RequestUrlParam): Promise<string> => {
			if (stopReason) throw stopReason;
			let response;
			try {
				response = await requestUrl({ ...options, throw: false });
			} catch {
				if (stopReason) throw stopReason;
				throw new TranscriptServiceError("network", "Could not connect to YouTube. Check your connection and try again.");
			}
			if (stopReason) throw stopReason;
			if (response.status === 429 || response.status === 403 || response.status === 401) {
				throw new TranscriptServiceError("blocked", "YouTube is temporarily blocking transcript requests. Please try again later.");
			}
			if (response.status < 200 || response.status >= 300) {
				throw new TranscriptServiceError("network", `YouTube could not return the transcript (HTTP ${response.status}). Please try again later.`);
			}
			if (response.text.length > MAX_RESPONSE_LENGTH) throw invalidResponse();
			return response.text;
		};

		const fetch = async (): Promise<VideoTranscript> => {
			const html = await request({ url: `${YOUTUBE_ORIGIN}/watch?v=${videoId}`, method: "GET" });
			const apiKey = html.match(/"INNERTUBE_API_KEY"\s*:\s*"([^"\\]+)"/)?.[1];
			const visitorData = html.match(/"VISITOR_DATA"\s*:\s*"([^"\\]+)"/)?.[1];
			// The public page's key is YouTube's bootstrap configuration, not the user's
			// Google API key. No OAuth tokens or browser cookies are sent by this service.
			const player = apiKey
				? parseJson(await request({
					url: `${YOUTUBE_ORIGIN}/youtubei/v1/player?key=${encodeURIComponent(apiKey)}`,
					method: "POST",
					contentType: "application/json",
					body: JSON.stringify({
						videoId,
						context: { client: { clientName: "ANDROID", clientVersion: "20.10.38", hl: "en", ...(visitorData ? { visitorData } : {}) } },
					}),
				}))
				: readPlayerFromHtml(html);
			const track = selectTrack(readTracks(player), preferredLanguage);
			let captionUrl: URL;
			try {
				captionUrl = new URL(track.baseUrl);
			} catch {
				throw invalidResponse();
			}
			if (captionUrl.protocol !== "https:" || !["www.youtube.com", "youtube.com"].includes(captionUrl.hostname)
				|| captionUrl.pathname !== "/api/timedtext" || captionUrl.username || captionUrl.password || captionUrl.port) throw invalidResponse();
			const text = await request({ url: captionUrl.href, method: "GET" });
			return { videoId, language: track.language, languageName: track.languageName, isAutoGenerated: track.isAutoGenerated, segments: parseTranscript(text) };
		};

		try {
			return await Promise.race([fetch(), stopped]);
		} finally {
			if (timeoutId !== undefined) clearTimeout(timeoutId);
			if (abortListener) signal?.removeEventListener("abort", abortListener);
		}
	}
}

export const transcriptService = new TranscriptService();
