import type { View } from "obsidian";
import type { TranscriptSegment, VideoTranscript } from "./transcriptService";

interface TranscriptWebview extends HTMLElement {
	getURL(): string;
	executeJavaScript(code: string): Promise<unknown>;
}

const PANEL_TIMEOUT_MS = 8000;

function record(value: unknown): Record<string, unknown> | undefined {
	return typeof value === "object" && value !== null && !Array.isArray(value)
		? value as Record<string, unknown>
		: undefined;
}

export function videoIdFromUrl(value: unknown): string | null {
	if (typeof value !== "string") return null;
	try {
		const url = new URL(value);
		if (url.protocol !== "https:" || !["www.youtube.com", "youtube.com", "m.youtube.com"].includes(url.hostname)) return null;
		return url.pathname === "/watch" ? url.searchParams.get("v") : url.pathname.match(/^\/(?:shorts|live|embed)\/([\w-]{11})\/?$/)?.[1] ?? null;
	} catch {
		return null;
	}
}

function browserScript(videoId: string, cancelEvent: string): string {
	return `(() => {
		const videoId = ${JSON.stringify(videoId)};
		const cancelEvent = ${JSON.stringify(cancelEvent)};
		const currentVideo = () => {
			if (!['https://www.youtube.com', 'https://youtube.com', 'https://m.youtube.com'].includes(location.origin)) return false;
			const id = location.pathname === '/watch' ? new URL(location.href).searchParams.get('v')
				: location.pathname.match(/^\\/(?:shorts|live|embed)\\/([\\w-]{11})\\/?$/)?.[1];
			return id === videoId;
		};
		const text = value => typeof value?.simpleText === 'string' ? value.simpleText
			: Array.isArray(value?.runs) && value.runs.every(run => typeof run.text === 'string')
				? value.runs.map(run => run.text).join('') : null;
		const snapshot = () => {
			const player = document.getElementById('movie_player')?.getPlayerResponse?.();
			if (player?.videoDetails?.videoId !== videoId) return null;
			const panel = document.querySelector('ytd-transcript-search-panel-renderer')?.data;
			const list = panel?.body?.transcriptSegmentListRenderer;
			const items = list?.initialSegments;
			// Use the complete list backing the panel, not just its visible rows.
			// Unknown/continued lists must never be used as full transcripts.
			if (!Array.isArray(items) || !items.length || items.length > 50000 || list.continuations?.length) return null;
			if (items.some(item => !item?.transcriptSegmentRenderer && !item?.transcriptSectionHeaderRenderer)) return null;
			const selected = panel?.footer?.transcriptFooterRenderer?.languageMenu?.sortFilterSubMenuRenderer?.subMenuItems?.find(item => item.selected);
			const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
			if (!selected || !Array.isArray(tracks)) return null;
			const matches = tracks.filter(track => text(track.name) === selected.title);
			if (matches.length !== 1 || typeof matches[0].languageCode !== 'string') return null;
			const track = matches[0];
			const cues = items.filter(item => item.transcriptSegmentRenderer).map(item => item.transcriptSegmentRenderer);
			if (!cues.length) return null;
			const trackId = cues[0].targetId?.split('.')[1];
			if (!trackId || cues.some(cue => typeof cue.targetId !== 'string'
				|| !cue.targetId.startsWith(videoId + '.' + trackId + '.'))) return null;
			return {
				videoId, language: track.languageCode, languageName: selected.title,
				isAutoGenerated: track.kind === 'asr', expectedSegmentCount: cues.length,
				segments: cues.map(cue => ({ startMs: cue.startMs, endMs: cue.endMs, text: text(cue.snippet) })),
			};
		};
		if (!currentVideo()) return null;
		return new Promise(resolve => {
			let finished = false;
			let expanded = false;
			let clicked = false;
			let checking = false;
			let observer;
			let timer;
			let deadline;
			const finish = value => {
				if (finished) return;
				finished = true;
				observer?.disconnect();
				clearInterval(timer);
				clearTimeout(deadline);
				window.removeEventListener(cancelEvent, cancel);
				resolve(value);
			};
			const cancel = () => finish(null);
			const check = () => {
				if (finished || checking) return;
				checking = true;
				try {
					if (!currentVideo()) { finish(null); return; }
					const result = snapshot();
					if (result) { finish(result); return; }
					if (!clicked) {
						const button = document.querySelector('ytd-video-description-transcript-section-renderer button');
						if (button instanceof HTMLElement && !button.disabled) {
							clicked = true;
							button.click();
						} else if (!expanded) {
							const expand = document.querySelector('ytd-watch-metadata #description-inline-expander #expand');
							if (expand instanceof HTMLElement) {
								expanded = true;
								expand.click();
							}
						}
					}
				} catch { finish(null); }
				finally { checking = false; }
			};
			window.addEventListener(cancelEvent, cancel, { once: true });
			observer = new MutationObserver(check);
			observer.observe(document.documentElement, { childList: true, subtree: true });
			timer = setInterval(check, 150);
			deadline = setTimeout(cancel, ${PANEL_TIMEOUT_MS});
			check();
		});
	})()`;
}

function parseTranscript(value: unknown, videoId: string): VideoTranscript | null {
	const data = record(value);
	if (!data || data.videoId !== videoId || typeof data.language !== "string" || !data.language.trim()
		|| typeof data.languageName !== "string" || !data.languageName.trim() || typeof data.isAutoGenerated !== "boolean"
		|| !Array.isArray(data.segments) || !data.segments.length || data.segments.length !== data.expectedSegmentCount) return null;
	const segments: TranscriptSegment[] = [];
	for (const value of data.segments) {
		const cue = record(value);
		if (!cue || typeof cue.text !== "string" || !cue.text.trim()
			|| typeof cue.startMs !== "string" || !/^\d+$/.test(cue.startMs)
			|| typeof cue.endMs !== "string" || !/^\d+$/.test(cue.endMs)) return null;
		const startMs = Number(cue.startMs);
		const endMs = Number(cue.endMs);
		if (!Number.isSafeInteger(startMs) || !Number.isSafeInteger(endMs) || endMs < startMs
			|| (segments.length > 0 && startMs / 1000 < segments[segments.length - 1].start)) return null;
		segments.push({ start: startMs / 1000, duration: (endMs - startMs) / 1000, text: cue.text.trim() });
	}
	return { videoId, language: data.language, languageName: data.languageName, isAutoGenerated: data.isAutoGenerated, segments };
}

export async function readWebViewerTranscript(view: View, videoId: string, signal?: AbortSignal): Promise<VideoTranscript | null> {
	if (signal?.aborted) throw new DOMException("Request aborted", "AbortError");
	const candidate = view.containerEl.querySelector("webview") as Partial<TranscriptWebview> | null;
	if (typeof candidate?.getURL !== "function" || typeof candidate.executeJavaScript !== "function") return null;
	if (videoIdFromUrl(candidate.getURL()) !== videoId) return null;
	const cancelEvent = "geulo-cancel-transcript-" + crypto.randomUUID();
	let onAbort: () => void = () => {};
	let timeout: number | undefined;
	const stopped = new Promise<never>((_, reject) => {
		const stop = (): void => {
			void Promise.resolve().then(() => candidate.executeJavaScript?.("window.dispatchEvent(new Event(" + JSON.stringify(cancelEvent) + "))")).catch(() => {});
		};
		onAbort = () => { stop(); reject(new DOMException("Request aborted", "AbortError")); };
		signal?.addEventListener("abort", onAbort, { once: true });
		// Bound the host wait too: the guest renderer may be suspended or destroyed.
		timeout = window.setTimeout(() => { stop(); reject(new Error("YouTube transcript panel timed out")); }, PANEL_TIMEOUT_MS + 1000);
	});
	try {
		const value = await Promise.race([candidate.executeJavaScript(browserScript(videoId, cancelEvent)), stopped]);
		if (signal?.aborted) throw new DOMException("Request aborted", "AbortError");
		if (videoIdFromUrl(candidate.getURL()) !== videoId) return null;
		return parseTranscript(value, videoId);
	} finally {
		window.clearTimeout(timeout);
		signal?.removeEventListener("abort", onAbort);
	}
}
