import { useEffect, useRef, useState } from "react";
import { App, getLanguage, Notice } from "obsidian";
import { TranscriptService, TranscriptServiceError } from "../services/transcriptService";
import type { VideoTranscript } from "../services/transcriptService";
import { ReactModal } from "./ReactModal";

type TranscriptState =
	| { kind: "loading" }
	| { kind: "loaded"; transcript: VideoTranscript }
	| { kind: "error"; message: string };

function formatTimestamp(seconds: number): string {
	const wholeSeconds = Math.floor(seconds);
	const hours = Math.floor(wholeSeconds / 3600);
	const minutes = Math.floor((wholeSeconds % 3600) / 60);
	const remainder = (wholeSeconds % 60).toString().padStart(2, "0");
	return hours > 0
		? `${hours}:${minutes.toString().padStart(2, "0")}:${remainder}`
		: `${minutes}:${remainder}`;
}

function VideoTranscriptContent({ videoId, videoTitle, service }: {
	videoId: string;
	videoTitle: string;
	service: TranscriptService;
}) {
	const contentRef = useRef<HTMLDivElement>(null);
	const [requestVersion, setRequestVersion] = useState(0);
	const [state, setState] = useState<TranscriptState>({ kind: "loading" });

	useEffect(() => {
		contentRef.current?.focus({ preventScroll: true });
	}, []);

	useEffect(() => {
		const controller = new AbortController();
		setState({ kind: "loading" });
		void service.fetchTranscript(videoId, controller.signal, getLanguage()).then(
			(transcript) => {
				if (!controller.signal.aborted) setState({ kind: "loaded", transcript });
			},
			(error: unknown) => {
				if (controller.signal.aborted) return;
				setState({
					kind: "error",
					message: error instanceof TranscriptServiceError
						? error.message
						: "Could not fetch the transcript. Please try again.",
				});
			},
		);
		return () => controller.abort();
	}, [videoId, service, requestVersion]);

	const copyTranscript = async (transcript: VideoTranscript): Promise<void> => {
		try {
			await navigator.clipboard.writeText(transcript.segments.map((segment) => segment.text).join("\n"));
			new Notice("Transcript copied to clipboard");
		} catch {
			new Notice("Could not copy the transcript. You can select and copy the text below.");
		}
	};

	return (
		<div ref={contentRef} className="video-transcript-modal" tabIndex={-1} aria-label={`Transcript for ${videoTitle}`}>
			<p className="video-transcript-modal__title">{videoTitle}</p>
			{state.kind === "loading" && <p role="status">Fetching transcript…</p>}
			{state.kind === "error" && (
				<div role="alert">
					<p>{state.message}</p>
					<button type="button" onClick={() => setRequestVersion((version) => version + 1)}>Try again</button>
				</div>
			)}
			{state.kind === "loaded" && (
				<>
					<div className="video-transcript-modal__toolbar">
						<span>{state.transcript.languageName}{state.transcript.isAutoGenerated ? " · Auto-generated captions" : " · Captions"}</span>
						<button type="button" onClick={() => void copyTranscript(state.transcript)}>Copy transcript</button>
					</div>
					<div className="video-transcript-modal__segments" aria-label="Transcript" tabIndex={0}>
						{state.transcript.segments.map((segment, index) => (
							<p className="video-transcript-modal__segment" key={index}>
								<a href={`https://www.youtube.com/watch?v=${videoId}&t=${Math.floor(segment.start)}`} target="_blank" rel="noopener noreferrer" aria-label={`Open video at ${formatTimestamp(segment.start)}`}>
									{formatTimestamp(segment.start)}
								</a>
								<span>{segment.text}</span>
							</p>
						))}
					</div>
				</>
			)}
		</div>
	);
}

export class VideoTranscriptModal extends ReactModal {
	constructor(app: App, videoId: string, videoTitle: string, onClose: () => void) {
		super(
			app,
			<VideoTranscriptContent videoId={videoId} videoTitle={videoTitle} service={new TranscriptService()} />,
			{ title: "Transcript", width: "700px", height: "min(760px, 80vh)", onClose },
		);
		this.modalEl.addClass("geulo-video-transcript-dialog");
	}
}
