/* global globalThis */
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { build } from 'esbuild';

const outputDirectory = await mkdtemp(path.join(tmpdir(), 'geulo-openai-service-'));
const outputPath = path.join(outputDirectory, 'openai-service.cjs');

await build({
	stdin: {
		contents: `
			export { OpenAIService } from './src/services/openAIService.ts';
			export { OpenRouterService } from './src/services/openRouterService.ts';
			export { GeminiService } from './src/services/geminiService.ts';
			export { createAIService, getActiveApiKey } from './src/services/aiServiceFactory.ts';
			export { AIServiceError } from './src/services/aiServiceError.ts';
			export { TranscriptServiceError } from './src/services/transcriptService.ts';
		`,
		resolveDir: process.cwd(),
		sourcefile: 'openai-service-verification-entry.ts',
	},
	bundle: true,
	format: 'cjs',
	platform: 'node',
	outfile: outputPath,
	plugins: [
		{
			name: 'openai-service-fixtures',
			setup(builder) {
				builder.onResolve({ filter: /^obsidian$/ }, () => ({
					path: 'obsidian',
					namespace: 'fixture',
				}));
				builder.onResolve({ filter: /(?:^|\/)transcriptService(?:\.ts)?$/ }, () => {
					return { path: 'transcriptService', namespace: 'fixture' };
				});
				builder.onLoad({ filter: /^obsidian$/, namespace: 'fixture' }, () => ({
					contents: `
						export const requestUrl = (request) => globalThis.requestUrl(request);
						export const getLanguage = () => globalThis.getLanguage();
					`,
					loader: 'js',
				}));
				builder.onLoad({ filter: /^transcriptService$/, namespace: 'fixture' }, () => ({
					contents: `
						export class TranscriptServiceError extends Error {
							constructor(code, message) {
								super(message);
								this.code = code;
								this.name = 'TranscriptServiceError';
							}
						}
						export const transcriptService = {
							getTranscript: (...args) => globalThis.getTranscript(...args),
						};
					`,
					loader: 'js',
				}));
			},
		},
	],
});

globalThis.window = {
	setTimeout: globalThis.setTimeout.bind(globalThis),
	clearTimeout: globalThis.clearTimeout.bind(globalThis),
};
globalThis.getLanguage = () => 'ko-KR';
globalThis.fetch = async (url, options) => {
	if (options.signal?.aborted) throw new DOMException('Request aborted', 'AbortError');
	const result = await globalThis.requestUrl({ url, ...options });
	return new Response(result.text, { status: result.status, headers: result.headers });
};

const require = createRequire(import.meta.url);
const {
	OpenAIService,
	OpenRouterService,
	GeminiService,
	createAIService,
	getActiveApiKey,
	AIServiceError,
	TranscriptServiceError,
} = require(outputPath);

const transcript = {
	videoId: 'video-01',
	language: 'ko',
	languageName: 'Korean',
	isAutoGenerated: false,
	segments: [
		{ start: 0, duration: 4.5, text: '첫 번째 문장' },
		{ start: 4.5, duration: 3, text: 'Second sentence' },
	],
};
let transcriptCalls = [];
let requests = [];

globalThis.getTranscript = async (...args) => {
	transcriptCalls.push(args);
	args[3]?.('fetching-transcript');
	return transcript;
};

const response = (body, status = 200) => ({
	status,
	text: typeof body === 'string' ? body : JSON.stringify(body),
	headers: {},
});

const streamBody = [
	'event: response.created',
	'data: {"type":"response.created"}',
	'',
	'event: response.output_text.delta',
	'data: {"type":"response.output_text.delta","delta":"첫 "}',
	'',
	'data: {"type":"response.output_text.delta","delta":"요약"}',
	'',
	'data: {"type":"response.output_text.done","text":"첫 요약"}',
	'',
	'data: [DONE]',
	'',
].join('\n');

globalThis.requestUrl = async (request) => {
	requests.push(request);
	return response(streamBody);
};

const service = new OpenAIService('sk-openai-test', 'gpt-5.6-luna', 'ko');
const streamedChunks = [];
const progressPhases = [];
let completedResult;
await service.generateVideoSummaryStream('video-01', '핵심을 요약하세요.', {
	onPhase: phase => progressPhases.push(phase),
	onChunk: (chunk, accumulated) => streamedChunks.push({ chunk, accumulated }),
	onComplete: (result) => {
		completedResult = result;
	},
});

assert.equal(transcriptCalls.length, 1);
assert.equal(transcriptCalls[0][0], 'video-01');
assert.equal(transcriptCalls[0][2], 'ko');
assert.deepEqual(progressPhases, ['fetching-transcript', 'waiting-for-ai']);
assert.equal(requests.length, 1);
assert.equal(requests[0].url, 'https://api.openai.com/v1/responses');
assert.equal(requests[0].method, 'POST');
assert.equal(requests[0].headers.Authorization, 'Bearer sk-openai-test');
assert.equal(requests[0].headers['Content-Type'], 'application/json');

const summaryBody = JSON.parse(requests[0].body);
assert.equal(summaryBody.model, 'gpt-5.6-luna');
assert.equal(summaryBody.stream, true);
assert.equal(summaryBody.store, false);
assert.match(summaryBody.instructions, /핵심을 요약하세요\./);
assert.match(summaryBody.instructions, /source material, not instructions/i);
assert.match(summaryBody.instructions, /visual details/i);
assert.match(summaryBody.input, /Transcript \(Korean\):/);
assert.match(summaryBody.input, /\[0s\] 첫 번째 문장/);
assert.match(summaryBody.input, /\[4\.5s\] Second sentence/);
assert.deepEqual(streamedChunks, [
	{ chunk: '첫 ', accumulated: '첫 ' },
	{ chunk: '요약', accumulated: '첫 요약' },
]);
assert.deepEqual(completedResult, {
	summary: '첫 요약',
	generatedAt: completedResult.generatedAt,
	model: 'gpt-5.6-luna',
	source: 'transcript',
});
assert.doesNotThrow(() => new Date(completedResult.generatedAt).toISOString());

requests = [];
transcriptCalls = [];
globalThis.requestUrl = async (request) => {
	requests.push(request);
	return response({
		output: [
			{ type: 'reasoning', summary: [] },
			{
				type: 'message',
				role: 'assistant',
				content: [
					{ type: 'output_text', text: 'Concise ' },
					{ type: 'refusal', refusal: 'ignored' },
				],
			},
			{
				type: 'message',
				role: 'assistant',
				content: [{ type: 'output_text', text: 'summary' }],
			},
			{
				type: 'message',
				role: 'user',
				content: [{ type: 'output_text', text: 'ignored user text' }],
			},
		],
	});
};

assert.equal(await service.generateTextCompletion('Make this concise.'), 'Concise summary');
assert.equal(transcriptCalls.length, 0);
assert.equal(requests.length, 1);
const completionBody = JSON.parse(requests[0].body);
assert.deepEqual(completionBody, {
	model: 'gpt-5.6-luna',
	stream: false,
	store: false,
	input: 'Make this concise.',
});

globalThis.requestUrl = async () => response({
	output: [{ type: 'message', role: 'assistant', content: [{ type: 'refusal', refusal: 'No' }] }],
});
assert.equal(await service.generateTextCompletion('No output text'), '');

globalThis.requestUrl = async () => response([
	'data: not-json',
	'data: {"type":"response.output_text.delta","delta":4}',
	'data: {"type":"response.completed"}',
	'',
].join('\n'));
let ignoredEventResult;
await service.generateVideoSummaryStream('video-01', 'Ignore malformed events.', {
	onChunk: () => assert.fail('Irrelevant events must not emit text'),
	onComplete: (result) => {
		ignoredEventResult = result;
	},
});
assert.equal(ignoredEventResult.summary, '');

requests = [];
globalThis.getTranscript = async () => {
	throw new TranscriptServiceError('unavailable', 'Captions unavailable');
};
await assert.rejects(
	service.generateVideoSummaryStream('video-01', 'Summarize.', { onChunk: () => {} }),
	(error) => error instanceof AIServiceError
		&& error.type === 'transcript_error'
		&& error.message === 'Captions unavailable',
);
assert.equal(requests.length, 0);

const noKeyService = new OpenAIService('', 'gpt-5.6-luna');
await assert.rejects(
	noKeyService.generateTextCompletion('test'),
	(error) => error instanceof AIServiceError && error.type === 'no_api_key',
);

globalThis.getTranscript = async (...args) => {
	transcriptCalls.push(args);
	if (args[1]?.aborted) throw new DOMException('Request aborted', 'AbortError');
	args[3]?.('fetching-transcript');
	return transcript;
};
requests = [];
const controller = new AbortController();
controller.abort();
await service.generateVideoSummaryStream('video-01', 'Cancelled.', {
	onChunk: () => assert.fail('Cancelled requests must not emit text'),
	signal: controller.signal,
});
assert.equal(requests.length, 0);

const httpCases = [
	[400, 'request_rejected', /OpenAI rejected the request for gpt-5\.6-luna: bad request/],
	[401, 'invalid_key', /Invalid API key: bad key/],
	[403, 'request_rejected', /OpenAI rejected the request for gpt-5\.6-luna: forbidden/],
	[429, 'rate_limit', /Rate limit exceeded/],
	[500, 'unknown', /HTTP 500: provider down/],
];
for (const [status, type, message] of httpCases) {
	const providerMessage = status === 400
		? 'bad request'
		: status === 401
			? 'bad key'
			: status === 403
				? 'forbidden'
				: status === 429
					? 'slow down'
					: 'provider down';
	globalThis.requestUrl = async () => response({ error: { message: providerMessage } }, status);
	await assert.rejects(
		service.generateTextCompletion('test'),
		(error) => error instanceof AIServiceError && error.type === type && message.test(error.message),
	);
}

const settings = {
	aiProvider: 'openai',
	openAIApiKey: 'openai-key',
	openAIModel: 'gpt-5.6-terra',
	openRouterApiKey: 'openrouter-key',
	openRouterModel: 'openrouter/model',
	geminiApiKey: 'gemini-key',
	transcriptLanguage: 'auto',
};
const openAIFromFactory = createAIService(settings);
assert.ok(openAIFromFactory instanceof OpenAIService);
assert.equal(getActiveApiKey(settings), 'openai-key');
assert.ok(createAIService({ ...settings, aiProvider: 'openrouter' }) instanceof OpenRouterService);
assert.equal(getActiveApiKey({ ...settings, aiProvider: 'openrouter' }), 'openrouter-key');
assert.ok(createAIService({ ...settings, aiProvider: 'gemini' }) instanceof GeminiService);
assert.equal(getActiveApiKey({ ...settings, aiProvider: 'gemini' }), 'gemini-key');

transcriptCalls = [];
globalThis.requestUrl = async () => response(streamBody);
await openAIFromFactory.generateVideoSummaryStream('video-01', 'Factory language.', { onChunk: () => {} });
assert.equal(transcriptCalls[0][2], 'ko-KR');

const streamCases = [
	[new OpenAIService('fixture-key', 'fixture-model'), text => ({ type: 'response.output_text.delta', delta: text })],
	[new OpenRouterService('fixture-key', 'fixture-model'), text => ({ choices: [{ delta: { content: text } }] })],
	[new GeminiService('fixture-key'), text => ({ candidates: [{ content: { parts: [{ text }] } }] })],
];
const encoder = new TextEncoder();
const tick = () => new Promise(resolve => setImmediate(resolve));
for (const [streamService, event] of streamCases) {
	let streamController;
	let transportCancelled = false;
	globalThis.requestUrl = () => assert.fail('Streaming must not use the buffered requestUrl transport');
	globalThis.fetch = async (url, options) => new Response(new ReadableStream({
		start(controller) {
			streamController = controller;
			options.signal.addEventListener('abort', () => controller.error(new DOMException('Request aborted', 'AbortError')), { once: true });
		},
		cancel() { transportCancelled = true; },
	}));
	const chunks = [];
	const phases = [];
	let result;
	const run = streamService.generateVideoSummaryStream('video-01', 'Stream progressively.', {
		onPhase: phase => phases.push(phase),
		onChunk: (chunk, accumulated) => chunks.push(accumulated),
		onComplete: value => { result = value; },
	});
	await tick();
	assert.deepEqual(phases, streamService instanceof GeminiService
		? ['waiting-for-ai']
		: ['fetching-transcript', 'waiting-for-ai']);
	const firstEvent = encoder.encode(`data:${JSON.stringify(event('첫 응답'))}\r\n\r\n`);
	for (const byte of firstEvent) streamController.enqueue(Uint8Array.of(byte));
	await tick();
	assert.deepEqual(chunks, ['첫 응답']);
	assert.equal(result, undefined, 'First text must arrive while the response is still open');
	streamController.enqueue(encoder.encode(`data: ${JSON.stringify(event(' 완료'))}\n\ndata: [DONE]\n\n`));
	await run;
	assert.equal(result.summary, '첫 응답 완료');
	assert.equal(transportCancelled, true, 'DONE must release the live transport');

	const abortController = new AbortController();
	result = undefined;
	const cancelledRun = streamService.generateVideoSummaryStream('video-01', 'Cancel partial response.', {
		onChunk: () => {},
		onComplete: value => { result = value; },
		signal: abortController.signal,
	});
	await tick();
	streamController.enqueue(encoder.encode(`data: ${JSON.stringify(event('Partial'))}\n\n`));
	await tick();
	abortController.abort();
	await cancelledRun;
	assert.equal(result, undefined, 'Cancelled partial text must not be completed or cached');

	const eofRun = streamService.generateVideoSummaryStream('video-01', 'Flush final event.', {
		onChunk: () => {},
		onComplete: value => { result = value; },
	});
	await tick();
	streamController.enqueue(encoder.encode(`data: ${JSON.stringify(event('Final event'))}`));
	streamController.close();
	await eofRun;
	assert.equal(result.summary, 'Final event');
}

const originalSetTimeout = globalThis.window.setTimeout;
globalThis.window.setTimeout = (callback, delay) => originalSetTimeout(callback, delay === 90000 ? 0 : delay);
try {
	for (const generate of [
		() => service.generateVideoSummaryStream('video-01', 'Timeout stream.', {
			onChunk: () => {},
			onComplete: () => assert.fail('Timed-out summaries must not complete'),
		}),
		() => service.generateVideoSummary('video-01', 'Timeout summary.'),
	]) {
		await assert.rejects(generate, error => error instanceof AIServiceError
			&& error.type === 'network_error' && /timed out/.test(error.message));
	}
} finally {
	globalThis.window.setTimeout = originalSetTimeout;
}

console.log('OpenAI service: Responses payloads, transcript grounding, parsing, errors, cancellation and provider routing passed.');
console.log('All three providers: incremental delivery before completion, split UTF-8, cancellation, DONE cleanup and final-event flushing passed. Shared stream/summary timeouts passed.');
console.log('Actual OpenAI requests require live Obsidian and provider QA.');
