/* global globalThis */
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';

globalThis.window = globalThis;
const outputDirectory = await mkdtemp(path.join(tmpdir(), 'geulo-webviewer-transcript-'));
const outputPath = path.join(outputDirectory, 'webviewer-transcript.cjs');
await build({
	entryPoints: ['src/services/webViewerTranscriptService.ts'],
	bundle: true, format: 'cjs', platform: 'node', outfile: outputPath,
});
const require = createRequire(import.meta.url);
const { readWebViewerTranscript } = require(outputPath);
const videoId = 'testVideo01';

function panelData(count = 318) {
	return {
		body: { transcriptSegmentListRenderer: {
			initialSegments: Array.from({ length: count }, (_, i) => ({
				transcriptSegmentRenderer: {
					startMs: String(i * 2500 + 40), endMs: String(i * 2500 + 1760),
					targetId: videoId + '.track.' + i,
					snippet: { runs: [{ text: i === 0 ? '<b>Literal caption</b>' : 'Caption ' + i }] },
				},
			})),
		} },
		footer: { transcriptFooterRenderer: { languageMenu: { sortFilterSubMenuRenderer: {
			subMenuItems: [{ title: 'Korean (auto-generated)', selected: true }],
		} } } },
	};
}

function fixture({ data, url = 'https://www.youtube.com/watch?v=' + videoId, delayed = false } = {}) {
	const dom = new JSDOM('<div id="movie_player"></div><ytd-watch-metadata><div id="description-inline-expander"><button id="expand">More</button></div></ytd-watch-metadata><ytd-transcript-search-panel-renderer></ytd-transcript-search-panel-renderer>', { url, runScripts: 'outside-only' });
	const doc = dom.window.document;
	const panel = doc.querySelector('ytd-transcript-search-panel-renderer');
	panel.data = data;
	doc.getElementById('movie_player').getPlayerResponse = () => ({
		videoDetails: { videoId },
		captions: { playerCaptionsTracklistRenderer: { captionTracks: [
			{ languageCode: 'ko', name: { simpleText: 'Korean (auto-generated)' }, kind: 'asr' },
		] } },
	});
	const guestTimeout = dom.window.setTimeout.bind(dom.window);
	const guestInterval = dom.window.setInterval.bind(dom.window);
	dom.window.setTimeout = (fn, ms) => guestTimeout(fn, ms === 8000 ? 80 : ms);
	dom.window.setInterval = (fn) => guestInterval(fn, 5);
	let expanded = 0;
	let clicked = 0;
	let executions = 0;
	doc.getElementById('expand').onclick = () => {
		expanded++;
		if (!delayed) return;
		guestTimeout(() => {
			const section = doc.createElement('ytd-video-description-transcript-section-renderer');
			const button = doc.createElement('button');
			button.textContent = '스크립트 표시';
			button.onclick = () => {
				clicked++;
				const row = doc.createElement('ytd-transcript-segment-renderer');
				panel.appendChild(row);
				guestTimeout(() => {
					panel.data = panelData();
					panel.appendChild(doc.createElement('span'));
				}, 10);
			};
			section.appendChild(button);
			doc.body.appendChild(section);
		}, 5);
	};
	const webview = {
		getURL: () => dom.window.location.href,
		executeJavaScript: async code => { executions++; return dom.window.eval(code); },
	};
	return {
		dom, panel, webview,
		view: { containerEl: { querySelector: selector => selector === 'webview' ? webview : null } },
		counts: () => ({ expanded, clicked, executions }),
		close: () => dom.window.close(),
	};
}

const full = fixture({ data: panelData() });
full.panel.appendChild(full.dom.window.document.createElement('ytd-transcript-segment-renderer'));
const result = await readWebViewerTranscript(full.view, videoId);
assert.equal(result.segments.length, 318, 'The full backing list is read even with only one DOM row');
assert.equal(result.language, 'ko', 'The actual selected caption language is retained');
assert.equal(result.isAutoGenerated, true);
assert.deepEqual(result.segments[0], { start: 0.04, duration: 1.72, text: '<b>Literal caption</b>' });
assert.equal(result.segments.at(-1).start, 792.54);
assert.deepEqual(full.counts(), { expanded: 0, clicked: 0, executions: 1 });
full.close();

const delayed = fixture({ delayed: true });
const loaded = await readWebViewerTranscript(delayed.view, videoId);
assert.equal(loaded.segments.length, 318, 'A first DOM row is not treated as a full transcript');
assert.deepEqual(delayed.counts(), { expanded: 1, clicked: 1, executions: 1 });
delayed.close();

for (const mutate of [
	data => { data.body.transcriptSegmentListRenderer.initialSegments[1].transcriptSegmentRenderer.startMs = 'bad'; },
	data => { data.body.transcriptSegmentListRenderer.initialSegments[1].transcriptSegmentRenderer.snippet = {}; },
	data => { data.body.transcriptSegmentListRenderer.initialSegments[1].transcriptSegmentRenderer.targetId = 'otherVideo1.track.1'; },
	data => { data.body.transcriptSegmentListRenderer.initialSegments[1].transcriptSegmentRenderer.targetId = videoId + '.other-track.1'; },
	data => { data.body.transcriptSegmentListRenderer.initialSegments.push({ continuationItemRenderer: {} }); },
	data => { data.body.transcriptSegmentListRenderer.continuations = [{}]; },
	data => { data.footer.transcriptFooterRenderer.languageMenu.sortFilterSubMenuRenderer.subMenuItems[0].title = 'Unknown language'; },
	data => { data.body.transcriptSegmentListRenderer.initialSegments[1].transcriptSegmentRenderer.endMs = '1'; },
]) {
	const data = panelData(2);
	mutate(data);
	const invalid = fixture({ data });
	assert.equal(await readWebViewerTranscript(invalid.view, videoId), null, 'Malformed, mixed-video/track or partial data must not become a cached transcript');
	invalid.close();
}

const missing = fixture();
assert.equal(await readWebViewerTranscript(missing.view, videoId), null);
assert.equal(missing.counts().expanded, 1, 'Description expansion is attempted only once');
missing.close();

for (const url of ['https://www.youtube.com/watch?v=otherVideo1', 'https://example.com/watch?v=' + videoId]) {
	const wrong = fixture({ url });
	assert.equal(await readWebViewerTranscript(wrong.view, videoId), null);
	assert.equal(wrong.counts().executions, 0);
	wrong.close();
}

const navigating = fixture({ delayed: true });
const navigation = readWebViewerTranscript(navigating.view, videoId);
navigating.dom.window.history.replaceState(null, '', '/watch?v=otherVideo1');
assert.equal(await navigation, null, 'Navigation during the wait invalidates the result');
navigating.close();

const aborted = fixture({ delayed: true });
const controller = new AbortController();
const pending = readWebViewerTranscript(aborted.view, videoId, controller.signal);
controller.abort();
await assert.rejects(pending, error => error.name === 'AbortError');
await new Promise(resolve => setTimeout(resolve, 25));
assert.equal(aborted.counts().clicked, 0, 'Cancellation stops late automatic clicks');
aborted.close();

const beforeStart = fixture();
await assert.rejects(readWebViewerTranscript(beforeStart.view, videoId, controller.signal), error => error.name === 'AbortError');
assert.equal(beforeStart.counts().executions, 0);
beforeStart.close();

const detached = fixture();
const detachController = new AbortController();
detached.webview.executeJavaScript = () => new Promise(() => {});
const detaching = readWebViewerTranscript(detached.view, videoId, detachController.signal);
detached.webview.executeJavaScript = () => { throw new Error('Webview destroyed'); };
detachController.abort();
await assert.rejects(detaching, error => error.name === 'AbortError');
detached.close();

console.log('Web Viewer transcript: closed-panel auto-open, delayed full list, 318/318 completeness, exact timing, actual language, malformed/continued data rejection, navigation and cancellation passed.');
