/* global globalThis */
import assert from 'node:assert/strict';
import { mkdtemp } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { build } from 'esbuild';

const outputDirectory = await mkdtemp(path.join(tmpdir(), 'geulo-transcript-service-'));
const outputPath = path.join(outputDirectory, 'transcript-service.cjs');
await build({
	entryPoints: ['src/services/transcriptService.ts'],
	bundle: true,
	format: 'cjs',
	platform: 'node',
	outfile: outputPath,
	plugins: [{
		name: 'transcript-request-fixture',
		setup(builder) {
			builder.onResolve({ filter: /^obsidian$/ }, () => ({ path: 'obsidian', namespace: 'fixture' }));
			builder.onLoad({ filter: /.*/, namespace: 'fixture' }, () => ({
				contents: 'export const requestUrl = (request) => globalThis.requestUrl(request);',
				loader: 'js',
			}));
		},
	}],
});
const require = createRequire(import.meta.url);
const { TranscriptService, TranscriptServiceError } = require(outputPath);
const service = new TranscriptService();
const videoId = 'testVideo01';
const makeTrack = (languageCode, kind) => ({
	baseUrl: `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${languageCode}&kind=${kind ?? 'manual'}`,
	languageCode,
	name: { runs: [{ text: languageCode }] },
	kind,
});
const player = (tracks) => ({
	playabilityStatus: { status: 'OK' },
	captions: { playerCaptionsTracklistRenderer: { captionTracks: tracks } },
});
const captionBody = {
	events: [
		{ id: 1 },
		{ tStartMs: 1250, dDurationMs: 2400, segs: [{ utf8: 'Hello & ' }, { utf8: '<world> 안녕' }] },
		{ tStartMs: 4000, dDurationMs: 1000, segs: [{ utf8: '  \n' }] },
		{ tStartMs: 5000, segs: [{ utf8: 'Second line' }] },
	],
};
const response = (body, status = 200) => ({ status, text: typeof body === 'string' ? body : JSON.stringify(body) });
let requests = [];
const fixture = (tracks, captionResponse = response(captionBody), watchHtml = '"INNERTUBE_API_KEY":"public-key" "VISITOR_DATA":"visitor"') => {
	requests = [];
	globalThis.requestUrl = async (request) => {
		requests.push(request);
		if (request.url.includes('/watch?')) return response(watchHtml);
		if (request.url.includes('/youtubei/')) return response(player(tracks));
		return captionResponse;
	};
};
const rejectsWith = (code) => (error) => error instanceof TranscriptServiceError && error.code === code;

fixture([makeTrack('en'), makeTrack('ko', 'asr'), makeTrack('ko')]);
const result = await service.fetchTranscript(videoId, undefined, 'ko-KR');
assert.equal(result.language, 'ko');
assert.equal(result.isAutoGenerated, false);
assert.deepEqual(result.segments, [
	{ start: 1.25, duration: 2.4, text: 'Hello & <world> 안녕' },
	{ start: 5, duration: 0, text: 'Second line' },
]);
assert.equal(requests.length, 3);
assert.match(requests[1].url, /youtubei\/v1\/player\?key=public-key$/);
assert.equal(JSON.parse(requests[1].body).videoId, videoId);
assert.equal(JSON.parse(requests[1].body).context.client.clientName, 'ANDROID');
assert.equal(JSON.parse(requests[1].body).context.client.visitorData, 'visitor');
assert.ok(requests.every((request) => !request.headers?.Authorization && !request.headers?.Cookie));
assert.match(requests[2].url, /kind=manual/);

fixture([makeTrack('fr'), makeTrack('en', 'asr')]);
assert.equal((await service.fetchTranscript(videoId, undefined, 'ko')).language, 'en');
fixture([makeTrack('fr'), makeTrack('ja')]);
assert.equal((await service.fetchTranscript(videoId, undefined, 'ko')).language, 'fr');
fixture([makeTrack('ko', 'asr'), makeTrack('en')]);
assert.equal((await service.fetchTranscript(videoId, undefined, 'ko')).isAutoGenerated, true);

const fallbackPlayer = { ...player([makeTrack('en')]), videoDetails: { title: 'Braces } and escaped "quotes"' } };
fixture([], response(captionBody), `<script>var ytInitialPlayerResponse = ${JSON.stringify(fallbackPlayer)}; otherCode();</script>`);
assert.equal((await service.fetchTranscript(videoId)).segments.length, 2);
assert.equal(requests.length, 2);

fixture([]);
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('unavailable'));
fixture([makeTrack('en')], response(''));
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('blocked'));
fixture([makeTrack('en')], response('', 429));
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('blocked'));
fixture([makeTrack('en')], response({ events: [{ tStartMs: -1, segs: [{ utf8: 'bad' }] }] }));
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('invalid-response'));
fixture([makeTrack('en')], response({ events: [] }));
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('invalid-response'));
fixture([makeTrack('en')], response('{invalid-json'));
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('invalid-response'));

for (const baseUrl of ['http://www.youtube.com/api/timedtext', 'https://example.com/api/timedtext', 'https://www.youtube.com.evil.example/api/timedtext', 'https://www.youtube.com/watch?v=testVideo01']) {
	fixture([{ ...makeTrack('en'), baseUrl }]);
	await assert.rejects(service.fetchTranscript(videoId), rejectsWith('invalid-response'));
	assert.equal(requests.length, 2);
}
fixture([]);
await assert.rejects(service.fetchTranscript('invalid'), rejectsWith('unavailable'));
assert.equal(requests.length, 0);
globalThis.requestUrl = async () => { throw new Error('offline'); };
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('network'));
globalThis.requestUrl = async (request) => response(request.url.includes('/watch?')
	? '"INNERTUBE_API_KEY":"public-key"'
	: { playabilityStatus: { status: 'LOGIN_REQUIRED' } });
await assert.rejects(service.fetchTranscript(videoId), rejectsWith('blocked'));

const controller = new AbortController();
let finishWatch;
let requestCount = 0;
globalThis.requestUrl = () => {
	requestCount++;
	return new Promise((resolve) => { finishWatch = resolve; });
};
const pending = service.fetchTranscript(videoId, controller.signal);
controller.abort();
await assert.rejects(pending, (error) => error.name === 'AbortError');
finishWatch(response('"INNERTUBE_API_KEY":"public-key"'));
await new Promise((resolve) => setImmediate(resolve));
assert.equal(requestCount, 1);
await assert.rejects(service.fetchTranscript(videoId, controller.signal), (error) => error.name === 'AbortError');
assert.equal(requestCount, 1);

const realSetTimeout = globalThis.setTimeout;
globalThis.setTimeout = (callback) => realSetTimeout(callback, 0);
globalThis.requestUrl = () => new Promise(() => {});
try {
	await assert.rejects(service.fetchTranscript(videoId), rejectsWith('timeout'));
} finally {
	globalThis.setTimeout = realSetTimeout;
}
console.log('Transcript service: language selection, JSON3 parsing, HTML fallback, request safety, errors, abort and timeout passed.');
console.log('XML parsing and actual caption fetching require the Obsidian runtime QA.');
